# Generated by Django 5.0.6 on 2024-06-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('aadhaar', models.BigIntegerField()),
                ('phone', models.IntegerField()),
                ('customer_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
