# Generated by Django 5.0.6 on 2024-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_customeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings Account'), ('LOAN', 'Loan Account')], max_length=10),
        ),
    ]
